test with appium dia 2

diff --git a/.github/workflows/ci-automation.yml b/.github/workflows/ci-automation.yml
--- a/.github/workflows/ci-automation.yml
+++ b/.github/workflows/ci-automation.yml
@@ -44,6 +44,17 @@ jobs:
           java-version: '11'
           distribution: 'temurin'
           cache: gradle
+      - name: Clone repository
+        run: git clone --branch test-android-team git@github.com:99minutos/Automation_App_Veloz.git
+      - name: Copy APK
+        run: cp app-debug.apk Automation_App_Veloz/src/test/resources/app.apk
+      - name: Check if file exists 2
+        run: |
+          if [ ! -f Automation_App_Veloz/src/test/resources/app.apk ]; then
+            echo "File app-debug.apk not found2"
+            exit 1
+          fi
+          echo "File app-debug.apk found2"
       - name: run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
@@ -73,10 +84,6 @@ jobs:
         with:
           host: github.com
           private-key: ${{ secrets.PAT_ACTIONS }}
-      - name: Clone repository
-        run: git clone --branch test-android-team git@github.com:99minutos/Automation_App_Veloz.git
-      - name: Copy APK
-        run: cp app-debug.apk Automation_App_Veloz/src/test/resources/app.apk
 
       - name: Install Android SDK
         run: |
